# Physical wiring
topology:
  - left_node: mgmt01
    right_node: spine01
    left_role: management
    right_role: spine
    left_link: 1
    right_link: 2

  - left_node: mgmt01
    right_node: spine02
    left_role: management
    right_role: spine
    left_link: 3
    right_link: 4

  - left_node: mgmt01
    right_node: leaf01
    left_role: management
    right_role: leaf
    left_link: 5
    right_link: 6

  - left_node: mgmt01
    right_node: leaf02
    left_role: management
    right_role: leaf
    left_link: 7
    right_link: 8

  - left_node: mgmt01
    right_node: leaf03
    left_role: management
    right_role: leaf
    left_link: 9
    right_link: 10

  - left_node: mgmt01
    right_node: leaf04
    left_role: management
    right_role: leaf
    left_link: 11
    right_link: 12

  - left_node: mgmt01
    right_node: tower01
    left_role: management
    right_role: server
    left_link: 13
    right_link: 14

  - left_node: spine01
    right_node: leaf01
    left_role: spine
    right_role: leaf
    left_link: 15
    right_link: 16

  - left_node: spine01
    right_node: leaf02
    left_role: spine
    right_role: leaf
    left_link: 17
    right_link: 18

  - left_node: spine01
    right_node: leaf03
    left_role: spine
    right_role: leaf
    left_link: 19
    right_link: 20

  - left_node: spine01
    right_node: leaf04
    left_role: spine
    right_role: leaf
    left_link: 21
    right_link: 22

  - left_node: spine02
    right_node: leaf01
    left_role: spine
    right_role: leaf
    left_link: 23
    right_link: 24

  - left_node: spine02
    right_node: leaf02
    left_role: spine
    right_role: leaf
    left_link: 25
    right_link: 26

  - left_node: spine02
    right_node: leaf03
    left_role: spine
    right_role: leaf
    left_link: 27
    right_link: 28

  - left_node: spine02
    right_node: leaf04
    left_role: spine
    right_role: leaf
    left_link: 29
    right_link: 30
