---
## GCE Global
gce_debug: no
gce_region: europe-west1
gce_zone: europe-west1-d
gce_project_id: "darkbulb"
gce_service_account_email: "USERNAME@{{ project_id }}.iam.gserviceaccount.com"
gce_credentials_file: "keychain/darkbulb.json"

## GCE Instance
gce_cloud_instance_debug: "{{ gce_debug }}"
gce_cloud_instance_region: "{{ gce_region }}"
gce_cloud_instance_zone: "{{ gce_zone }}"
gce_cloud_instance_project_id: "{{ gce_project_id }}"
gce_cloud_instance_service_account_email: "{{ gce_service_account_email }}"
gce_cloud_instance_credentials_file: "{{ gce_credentials_file }}"
gce_cloud_instance_machine_type: n1-standard-1
gce_cloud_instance_image: nested-centos-7
gce_cloud_boot_disk_size: 30
gce_cloud_instance_tags: [ "darkbulb" ]
