---
dependencies: []

galaxy_info:
  author: victorock
  description: Google Cloud Engine
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  galaxy_tags:
    - general
