---
- name: "Assemble {{ underlay.conf|quote }}"
  assemble:
    src: "{{ underlay.build_dir }}"
    dest: "{{ underlay.conf }}"

- name: "Apply {{ underlay.conf|quote }}"
  junos_config:
    src: "{{ underlay.conf }}"
    backup: no
    update: override
