---
- name: "Virtualbox Repo is present"
  become: true
  yum_repository:
    name: virtualbox
    description: "Oracle Linux / RHEL / CentOS-$releasever / $basearch - VirtualBox"
    baseurl: "http://download.virtualbox.org/virtualbox/rpm/el/$releasever/$basearch"
    gpgcheck: no
## Workaround as 7.4 doesn't exists
#    enabled: yes
    enabled: no
##
    repo_gpgcheck: yes
    gpgkey: "https://www.virtualbox.org/download/oracle_vbox.asc"
  tags:
    - configure

- name: "Darkbulb Virtualbox packages state is latest"
  become: true
  yum:
    name: "{{ virtualbox_package }}"
    state: latest
    update_cache: yes
  with_items:
## Workaround as rpm for 7.4 doesn't exists
#    - VirtualBox-5.1
    - kernel-devel-3.10.0-693.2.2.el7.x86_64
    - http://download.virtualbox.org/virtualbox/rpm/rhel/7/x86_64/VirtualBox-5.1-5.1.8_111374_el7-1.x86_64.rpm
  loop_control:
    loop_var: virtualbox_package
    label: "{{ virtualbox_package }}"
  tags:
    - install

- name: "Check if virtualbox runs fine"
  become: true
  command: /usr/bin/VBoxManage --version
  register: vbox_version
  changed_when: false

- name: "Run vboxconfig to rebuild Virtualbox kernel modules"
  become: true
  command: /usr/sbin/vboxconfig
  when: "'vboxconfig' in vbox_version"

- name: "Ensure owner's is member of vboxusers"
  become: true
  user:
    name: "{{ owner }}"
    createhome: yes
    home: "/home/{{ owner }}"
    groups: vboxusers
    append: yes
  tags:
    - configure
