eos_conn:
  host: "{{ ansible_ssh_host }}"
  username: root
  password: vagrant
  transport: eapi
  port: "{{ eapi_port }}"
  validate_certs: no
  use_ssl: yes
  authorize: yes

provider: "{{ eos_conn }}"
