---
- name: "Ensure directory {{ assemble.config.build_dir }} is present"
  file:
    path: "{{ assemble.config.build_dir }}"
    state: directory

- name: "Ensure directory {{ assemble.config.conf_dir }} is present"
  file:
    path: "{{ assemble.config.conf_dir }}"
    state: directory

- name: "Assemble configurations from {{ assemble.config.build_dir }} to {{ assemble.config.conf }}"
  assemble:
    src: "{{ assemble.config.build_dir }}"
    dest: "{{ assemble.config.conf }}"
